### ISSUE TITLE
PHP Notice:  Undefined offset usb_model.php on line 212

### ISSUE THREAD

**Issue by precursorca** [munkireport/usb#5]
I see this in my web logs (i.p. obscured) with x's):
[php7:notice] [pid 92207] [client x.x.x.x:49823] PHP Notice:  Undefined offset: 1 in /Users/Shared/munkireport-php/vendor/munkireport/usb/usb_model.php on line 212

**Comment by tuxudo** [comment]
Caused by a USB device not having a vendor ID. Fixed by adding a check for vendor ID before processing it to extract the manufacturer. Should be resolved now
